#!/opt/bin/sh

# WireGuard interface only (iptables handled by netfilter.d)
ip link add dev wg0 type wireguard 2>/dev/null || true
wg setconf wg0 /opt/etc/wireguard/wg0.conf
ip addr add 10.50.0.1/24 dev wg0 2>/dev/null || true
ip link set wg0 mtu 1280
ip link set wg0 up

echo "WireGuard started"
